name: Deploy gh-pages

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE: /bus-signage-neo/
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Create xWER4
        env:
          ENV_1A: ${{ vars.ENV_1A }}
          ENV_2A: ${{ vars.ENV_2A }}
          ENV_2B: ${{ vars.ENV_2B }}
          ENV_3A: ${{ vars.ENV_3A }}
          ENV_3B: ${{ vars.ENV_3B }}
        run: |
          jq -cn \
            --arg v1a "$(printf '%s' "$ENV_1A" | base64 -w 0)" \
            --arg v2a "$(printf '%s' "$ENV_2A" | base64 -w 0)" \
            --arg v2b "$(printf '%s' "$ENV_2B" | base64 -w 0)" \
            --arg v3a "$(printf '%s' "$ENV_3A" | base64 -w 0)" \
            --arg v3b "$(printf '%s' "$ENV_3B" | base64 -w 0)" \
            '{
              "1a": $v1a,
              "2a": $v2a,
              "2b": $v2b,
              "3a": $v3a,
              "3b": $v3b
            }' |
            base64 -w 0 > dist/xWER4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4